// ========== DATA SECTION ==========

// Indore Companies Data
 const vijayNagarCompanies = [
        {
            name: "Golden Eagle IT Technologies",
            rating: 4.1,
            reviews: 43,
            address: "4th Floor, Plot No. 8, opposite chai coffee, Vijay Nagar, Indore, Madhya Pradesh 452010",
            hr_phone: "+91 9584309000",
            hr_phone: "+91 9584309001",
            email: "info@goldeneagleit.com",
            hr_email: "careers@goldeneagleit.com",
            website: "https://goldeneagleit.com",
            hours: "Open 24 hours",
            services: "IT Solutions, Software Development",
            employees: "50+",
            founded: "2018"
        },
        {
            name: "Beyond Key",
            rating: 4.6,
            reviews: 112,
            address: "901A, 9th Floor, NRK Business Park, PU4, Vijay Nagar Square, Indore, Madhya Pradesh 452010",
            hr_phone: "+91 731 4721700",
            hr_phone: "+91 731 4721701",
            email: "info@beyondkey.com",
            hr_email: "hr@beyondkey.com",
            website: "https://beyondkey.com",
            hours: "Opens 10 AM",
            services: "Software Development, IT Consulting",
            employees: "200+",
            founded: "2012",
            review: "Great place to work with excellent supportive leadership"
        },
        {
            name: "Dwellfox Private Limited",
            rating: 4.8,
            reviews: 99,
            address: "405, Apollo Premier, Vijay Nagar Square, Indore, Madhya Pradesh 452010",
            hr_phone: "+91 9303083558",
            hr_phone: "+91 9303083559",
            email: "contact@dwellfox.com",
            hr_email: "careers@dwellfox.com",
            website: "https://dwellfox.com",
            hours: "Opens 10 AM",
            services: "AI & ML, Staff Augmentation, ServiceNow, Salesforce",
            employees: "150+",
            founded: "2016",
            review: "Reliable and trustworthy company"
        },
        {
            name: "InTouch Software Solution",
            rating: 4.9,
            reviews: 28,
            address: "903, NRK Business Park, Vijay Nagar Square, Indore, Madhya Pradesh 452010",
            hr_phone: "+91 9691565883",
            hr_phone: "+91 9691565884",
            email: "needhelp@intouchsoftware.co.in",
            hr_email: "careers@intouchsoftware.co.in",
            website: "https://intouchsoftware.in",
            hours: "Opens 8:30 AM",
            services: "Website & Social Media Management",
            employees: "30+",
            founded: "2019"
        },
        {
            name: "Logical Soft Tech Private Limited",
            rating: 4.4,
            reviews: 148,
            address: "388, PU4, next to Krozzon Hotel, Vijay Nagar, Indore, Madhya Pradesh 452010",
            hr_phone: "+91 8210251824",
            hr_phone: "+91 7869731595",
            email: "info@logicalsofttech.com",
            hr_email: "hrlogicalsofttech@gmail.com",
            website: "https://logicalsofttech.com",
            hours: "Opens 10 AM",
            services: "Mobile App, Website Development, SEO/SMM",
            employees: "100+",
            founded: "2015"
        },
        {
            name: "Systology Software Pvt. Ltd.",
            rating: 4.9,
            reviews: 10,
            address: "5/3 Scheme No 54, Vijay Nagar, Indore, Madhya Pradesh 452010",
            hr_phone: "+91 9630904115",
            hr_phone: "+91 9630904116",
            email: "info@systology.co.in",
            hr_email: "careers@systology.co.in",
            website: "https://systology.co.in",
            hours: "Opens 9 AM",
            services: "IT Consulting"
        },
        {
            name: "Walkover Web Solutions Private Limited",
            rating: 4.1,
            reviews: 131,
            address: "5th Floor, LIC Tower, AB Rd, opposite Orbit Mall, Vijay Nagar, Indore",
            hr_phone: "+91 731 2560056",
            hr_phone: "+91 731 2560057",
            email: "info@walkover.in",
            hr_email: "hr@walkover.in",
            website: "https://walkover.in",
            hours: "Opens 9:30 AM",
            services: "Web Solutions",
            employees: "80+",
            founded: "2012"
        },
        {
            name: "Maven Cluster",
            rating: 4.3,
            reviews: 59,
            address: "173 PU4, Vijay Nagar, Indore, Madhya Pradesh 452010",
            hr_phone: "+91 9755555032",
            hr_phone: "+91 9755555033",
            email: "contact@mavencluster.com",
            hr_email: "careers@mavencluster.com",
            website: "https://mavencluster.com",
            hours: "Opens 10 AM",
            services: "Software Solutions"
        },
        {
            name: "Webgility",
            rating: 4.5,
            reviews: 48,
            address: "102 A-B, NRK Business Park, Vijay Nagar, Indore",
            hr_phone: "+91 8777535373",
            hr_phone: "+91 8777535374",
            email: "info@webgility.com",
            hr_email: "careers@webgility.com",
            website: "https://www.webgility.com",
            hours: "Opens 10 AM",
            services: "E-commerce Solutions"
        },
        {
            name: "The AVS Technology",
            rating: 4.5,
            reviews: 23,
            address: "LG49, Orbit Mall, near C21 Mall, Vijay Nagar, Indore",
            hr_phone: "+91 7440449139",
            hr_phone: "+91 7440449140",
            email: "info@theavstechnology.com",
            hr_email: "hr@theavstechnology.com",
            website: "https://theavstechnology.com",
            hours: "Opens 10 AM",
            services: "Software & Website Development"
        },
        {
            name: "Elicit Digital",
            rating: 4.7,
            reviews: 49,
            address: "Plot No. 345, 346, 3rd floor, Scheme 54 PU4, Vijay Nagar, Indore",
            hr_phone: "+91 9111555876",
            hr_phone: "+91 9111555877",
            email: "info@elicitdigital.com",
            hr_email: "careers@elicitdigital.com",
            website: "https://elicitdigital.com",
            hours: "Opens 10 AM",
            services: "AI-Driven Mobile App & Web Development"
        },
        {
            name: "Lemosys",
            rating: 4.3,
            reviews: 69,
            address: "Plot 169, Scheme 78, Part II, Behind Kanak Hospital, Vijay Nagar, Indore",
            hr_phone: "+91 731 4091887",
            hr_phone: "+91 731 4091888",
            email: "info@lemosys.com",
            hr_email: "careers@lemosys.com",
            website: "https://lemosys.com",
            hours: "Opens 9 AM",
            services: "Web Design & Development, IT Staff Augmentation"
        },
        {
            name: "Snayvik Tech Labs Private Limited",
            rating: 4.9,
            reviews: 26,
            address: "Krishna Business Center, 118, Plot No. 11, near Medanta Hospital, Vijay Nagar, Indore",
            hr_phone: "+91 7415519332",
            hr_phone: "+91 7415519333",
            email: "info@snayvik.com",
            hr_email: "careers@snayvik.com",
            website: "https://snayvik.com",
            hours: "Opens 9:30 AM",
            services: "Software Solutions"
        },
        {
            name: "FxBytes Technologies Pvt Ltd",
            rating: 4.1,
            reviews: 21,
            address: "Office No. 314, Shagun Tower A.B. Road, Vijay Nagar Square, Indore",
            hr_phone: "+91 731 4960000",
            hr_phone: "+91 731 4960001",
            email: "info@fxbytes.com",
            hr_email: "careers@fxbytes.com",
            website: "https://fxbytes.com",
            hours: "Opens 8 AM",
            services: "Software Development"
        },
        {
            name: "AT Technologies",
            rating: 5.0,
            reviews: 11,
            address: "Plot 30, First Floor, Scheme No 78 - III, Sector B, Vijay Nagar, Indore",
            hr_phone: "+91 731 4970000",
            hr_phone: "+91 731 4970001",
            email: "info@attechnologies.in",
            hr_email: "careers@attechnologies.in",
            website: "https://attechnologies.in",
            hours: "Opens 10 AM",
            services: "IT Solutions"
        },
        {
            name: "Shanti Infosoft LLP",
            rating: 4.8,
            reviews: 95,
            address: "1st-3rd floor PU4, Plot no 70, Vijay Nagar Square, Indore",
            hr_phone: "+91 9981225000",
            hr_phone: "+91 9981225001",
            email: "info@shantiinfosoft.com",
            hr_email: "careers@shantiinfosoft.com",
            website: "https://shantiinfosoft.com",
            hours: "Opens 10 AM",
            services: "AI / Web and App Design & Development"
        },
        {
            name: "HotWax Systems",
            rating: 4.2,
            reviews: 109,
            address: "80, Vijay Nagar, Indore",
            hr_phone: "+91 731 4093684",
            hr_phone: "+91 731 4093685",
            email: "info@hotwaxsystems.com",
            hr_email: "careers@hotwaxsystems.com",
            website: "https://www.hotwaxsystems.com",
            hours: "Opens 9 AM",
            services: "E-commerce Solutions"
        },
        {
            name: "EncoreSky Technologies Pvt Ltd",
            rating: 4.6,
            reviews: 63,
            address: "350, Vijay Nagar, Indore",
            hr_phone: "+91 731 4967837",
            hr_phone: "+91 731 4967838",
            email: "info@encoresky.com",
            hr_email: "careers@encoresky.com",
            website: "https://encoresky.com",
            hours: "Opens 10 AM",
            services: "Software Development"
        },
        {
            name: "Webllisto",
            rating: 4.7,
            reviews: 61,
            address: "801, Airen Heights, Vijay Nagar, Indore",
            hr_phone: "+91 9589849623",
            hr_phone: "+91 9589849624",
            email: "info@webllisto.com",
            hr_email: "careers@webllisto.com",
            website: "https://webllisto.com",
            hours: "Opens 10:30 AM",
            services: "Web Solutions"
        },
        {
            name: "Techcoopers Software Solutions Pvt. Ltd.",
            rating: 4.5,
            reviews: 28,
            address: "Plot No 8, 2nd Floor, Brilliant Platina, Vijay Nagar, Indore",
            hr_phone: "+91 731 4912780",
            hr_phone: "+91 731 4912781",
            email: "info@techcoopers.com",
            hr_email: "careers@techcoopers.com",
            website: "https://techcoopers.com",
            hours: "Opens 10 AM",
            services: "Software Development"
        },
        {
            name: "Techlene Software Solutions Pvt. Ltd.",
            rating: 4.1,
            reviews: 30,
            address: "P101, Metro Tower, Vijay Nagar Square, near Mangal city, Indore",
            hr_phone: "+91 7047575000",
            hr_phone: "+91 7047575001",
            email: "info@techlene.com",
            hr_email: "careers@techlene.com",
            website: "https://techlene.com",
            hours: "Opens 10 AM",
            services: "Software Solutions"
        },
        {
            name: "IntelliaTech Solutions Pvt Ltd",
            rating: 4.2,
            reviews: 60,
            address: "Plot No.120, near Ana Convent School, Vijay Nagar, Indore",
            hr_phone: "+91 731 4977140",
            hr_phone: "+91 731 4977141",
            email: "info@intelliatech.com",
            hr_email: "careers@intelliatech.com",
            website: "https://intelliatech.com",
            hours: "Opens 10 AM",
            services: "IT Solutions"
        },
        {
            name: "Hyperbeans Technologies Pvt Ltd",
            rating: 4.2,
            reviews: 59,
            address: "A-58, Basant Vihar, AB Rd, behind SBI, Indore",
            hr_phone: "+91 8962868389",
            hr_phone: "+91 8962868390",
            email: "info@hyperbeans.com",
            hr_email: "careers@hyperbeans.com",
            website: "https://hyperbeans.com",
            hours: "Opens 10:30 AM",
            services: "Software Development"
        },
        {
            name: "Simply Alliance Software Solutions Pvt Ltd.",
            rating: 4.8,
            reviews: 11,
            address: "104, 1st Floor, Vijay Nagar Square, Indore",
            hr_phone: "+91 731 4980000",
            hr_phone: "+91 731 4980001",
            email: "info@simplyalliance.com",
            hr_email: "careers@simplyalliance.com",
            website: "https://simplyalliance.com",
            hours: "Opens 11 AM",
            services: "Software Solutions"
        },
        {
            name: "Teclive Technology Pvt. Ltd.",
            rating: 4.9,
            reviews: 27,
            address: "EK 358 Scheme No 54, Vijay Nagar, Indore",
            hr_phone: "+91 9111118291",
            hr_phone: "+91 9111118292",
            email: "info@teclive.co.in",
            hr_email: "careers@teclive.co.in",
            website: "https://teclive.co.in",
            hours: "Opens 11 AM",
            services: "Software Development"
        },
        {
            name: "Evision Software Solutions Pvt. Ltd.",
            rating: 4.5,
            reviews: 18,
            address: "2nd Floor, 296 PU4, Commercial Scheme 54, behind Orbit Mall, Vijay Nagar, Indore",
            hr_phone: "+91 7999058883",
            hr_phone: "+91 7999058884",
            email: "info@evisionsoftware.in",
            hr_email: "careers@evisionsoftware.in",
            website: "https://evisionsoftware.in",
            hours: "Opens 10 AM",
            services: "Software Solutions"
        },
        {
            name: "ESP Softtech PVT LTD",
            rating: 4.8,
            reviews: 87,
            address: "601-602 Princess Business Skyline PU3, Vijay Nagar, Indore",
            hr_phone: "+91 8109784984",
            hr_phone: "+91 8109784985",
            email: "info@espsofttech.com",
            hr_email: "careers@espsofttech.com",
            website: "https://espsofttech.com",
            hours: "Opens 10 AM",
            services: "Blockchain Development"
        },
        {
            name: "Crackkart Infotech Pvt Ltd",
            rating: 4.9,
            reviews: 65,
            address: "AG-131 Scheme No.54, Vijay Nagar, Indore",
            hr_phone: "+91 7224077568",
            hr_phone: "+91 7224077569",
            email: "info@crackkart.com",
            hr_email: "careers@crackkart.com",
            website: "https://crackkart.com",
            hours: "Opens 9 AM",
            services: "E-commerce Solutions"
        },
        {
            name: "EasyComm Innovations Pvt Ltd",
            rating: 5.0,
            reviews: 52,
            address: "9th Floor, 902, Cliffton Corporate, Vijay Nagar, Indore",
            hr_phone: "+91 9244123567",
            hr_phone: "+91 9244123568",
            email: "info@easycomm.in",
            hr_email: "careers@easycomm.in",
            website: "https://easycomm.in",
            hours: "Opens 10 AM",
            services: "Software Solutions"
        },
        {
            name: "Bynebits Infotech Pvt. Ltd.",
            rating: 4.9,
            reviews: 31,
            address: "3rd Floor, Prestige Vihar, Vijay Nagar, Indore",
            hr_phone: "+91 8982815326",
            hr_phone: "+91 8982815327",
            email: "info@bynebits.com",
            hr_email: "careers@bynebits.com",
            website: "https://bynebits.com",
            hours: "Opens 10 AM",
            services: "Software Development"
        },
        {
            name: "Aahan Technologies",
            rating: 4.8,
            reviews: 40,
            address: "Vijay Nagar, Indore",
            hr_phone: "+91 8959362108",
            hr_phone: "+91 8959362109",
            email: "info@aahan.co.in",
            hr_email: "careers@aahan.co.in",
            website: "https://aahan.co.in",
            hours: "Opens 10 AM",
            services: "IT Solutions"
        },
        {
            name: "bluewebspark technologies",
            rating: 4.8,
            reviews: 20,
            address: "NRK Business Park, Vijay Nagar, Scheme No 54, Indore",
            hr_phone: "+91 731 5010000",
            hr_phone: "+91 731 5010001",
            email: "info@bluewebspark.com",
            hr_email: "careers@bluewebspark.com",
            website: "https://bluewebspark.com",
            hours: "Open 24 hours",
            services: "Web Solutions"
        },
        {
            name: "Softvyom Consulting Services Pvt. Ltd.",
            rating: 5.0,
            reviews: 25,
            address: "Shagun Arcade, 312, near Medanta Hospital, Vijay Nagar, Indore",
            hr_phone: "+91 731 5020000",
            hr_phone: "+91 731 5020001",
            email: "info@softvyom.com",
            hr_email: "careers@softvyom.com",
            website: "https://softvyom.com",
            hours: "Opens 10 AM",
            services: "Consulting & Development"
        },
        {
            name: "CYBEANS",
            rating: 5.0,
            reviews: 13,
            address: "1/12, Vijay Nagar Square, Indore",
            hr_phone: "+91 9406786739",
            hr_phone: "+91 9406786740",
            email: "info@cybeans.com",
            hr_email: "careers@cybeans.com",
            website: "https://cybeans.com",
            hours: "Opens 8 AM",
            services: "IT Solutions"
        },
        {
            name: "Techpanda IT Services",
            rating: 4.1,
            reviews: 43,
            address: "Plot Number 109-110 PU4, behind C21 Mall, Vijay Nagar, Indore",
            hr_phone: "+91 9009041407",
            hr_phone: "+91 9009041408",
            email: "info@techpanda.co.in",
            hr_email: "careers@techpanda.co.in",
            website: "https://techpanda.co.in",
            hours: "Opens 10 AM",
            services: "Software Development, Web & App Development"
        },
        {
            name: "Quintus Tech Pvt Ltd",
            rating: 4.8,
            reviews: 54,
            address: "Shagun Arcade, 505, Plot No-8, near Apna Sweets, Vijay Nagar, Indore",
            hr_phone: "+91 731 5030000",
            hr_phone: "+91 731 5030001",
            email: "info@quintustech.com",
            hr_email: "careers@quintustech.com",
            website: "https://quintustech.com",
            hours: "Opens 10 AM",
            services: "IT Solutions"
        },
        {
            name: "SSV Technologies",
            rating: 3.9,
            reviews: 65,
            address: "26, AB Rd, Scheme 54 PU4, Vijay Nagar, Indore",
            hr_phone: "+91 9039063936",
            hr_phone: "+91 9039063937",
            email: "info@ssvtechnologies.com",
            hr_email: "careers@ssvtechnologies.com",
            website: "https://ssvtechnologies.com",
            hours: "Opens 9:30 AM",
            services: "IT Services"
        },
        {
            name: "Techrefic Technologies Pvt. Ltd.",
            rating: 4.6,
            reviews: 26,
            address: "Virtual Coworks, 4th Floor, Mangal city, Vijay Nagar Square, Indore",
            hr_phone: "+91 9644488830",
            hr_phone: "+91 9644488831",
            email: "info@techrefic.com",
            hr_email: "careers@techrefic.com",
            website: "https://techrefic.com",
            hours: "Opens 10 AM",
            services: "IT Solutions"
        },
        {
            name: "Cognizant Technology Solutions India Pvt Ltd",
            rating: 4.8,
            reviews: 71,
            address: "3rd Floor, Brilliant Titanium, Plot No. 9, Vijay Nagar, Indore",
            hr_phone: "+91 731 5040000",
            hr_phone: "+91 731 5040001",
            email: "india.enquiry@cognizant.com",
            hr_email: "recruitment.india@cognizant.com",
            website: "https://www.cognizant.com",
            hours: "Opens 9 AM",
            services: "Enterprise IT Services"
        },
        {
            name: "Appstean Infotech Pvt. Ltd.",
            rating: 4.2,
            reviews: 66,
            address: "Skye Corporate Park, 603-604, Vijay Nagar, Indore",
            hr_phone: "+91 9644410244",
            hr_phone: "+91 9644410245",
            email: "info@appstean.com",
            hr_email: "careers@appstean.com",
            website: "https://appstean.com",
            hours: "Opens 10 AM",
            services: "Software Development"
        },
        {
            name: "CDN Solutions Group",
            rating: 3.8,
            reviews: 107,
            address: "Unit No. 304, Princes Business Skypark, AB Rd, Vijay Nagar, Indore",
            hr_phone: "+91 731 4035928",
            hr_phone: "+91 731 4035929",
            email: "info@cdnsol.com",
            hr_email: "careers@cdnsol.com",
            website: "https://www.cdnsol.com",
            hours: "Opens 10 AM",
            services: "IT Services"
        },
        {
            name: "TechForest Software Pvt. Ltd.",
            rating: 5.0,
            reviews: 30,
            address: "SCH. NO. 54, GF-7, near SICA School Road, Vijay Nagar, Indore",
            hr_phone: "+91 731 4907880",
            hr_phone: "+91 731 4907881",
            email: "info@techforest.in",
            hr_email: "careers@techforest.in",
            website: "https://techforest.in",
            hours: "Open 24 hours",
            services: "Hospital ERP, School ERP, App Development"
        },
        {
            name: "Webkorps Services India Private Limited",
            rating: 4.6,
            reviews: 72,
            address: "4th Floor, Winway World Offices, Vijay Nagar, Indore",
            hr_phone: "+91 731 5050000",
            hr_phone: "+91 731 5050001",
            email: "info@webkorps.com",
            hr_email: "careers@webkorps.com",
            website: "https://webkorps.com",
            hours: "Opens 10 AM",
            services: "IT Services"
        },
        {
            name: "SoftGetix - IT Staff Augmentation Services",
            rating: 4.4,
            reviews: 17,
            address: "519, Shagun Tower, Vijay Nagar Square, Indore",
            hr_phone: "+91 731 4002699",
            hr_phone: "+91 731 4002700",
            email: "info@softgetix.com",
            hr_email: "careers@softgetix.com",
            website: "https://softgetix.com",
            hours: "Opens 10 AM",
            services: "IT Staff Augmentation"
        },
        {
            name: "Techvalens Software Systems",
            rating: 4.1,
            reviews: 112,
            address: "410-OM Gurudev Plaza, Plot No.26 Scheme No.54, Vijay Nagar, Indore",
            hr_phone: "+91 9644506070",
            hr_phone: "+91 9644506071",
            email: "info@techvalens.com",
            hr_email: "careers@techvalens.com",
            website: "https://techvalens.com",
            hours: "Opens 10 AM",
            services: "Software Development"
        },
        {
            name: "DXC Technology",
            rating: 4.1,
            reviews: 286,
            address: "4th & 5th Floor, Brilliant Titanium, Plot No. 9, Scheme 78, Vijay Nagar, Indore",
            hr_phone: "+91 731 4430666",
            hr_phone: "+91 731 4430667",
            email: "info@dxc.com",
            hr_email: "careers@dxc.com",
            website: "https://dxc.com",
            hours: "Opens 9 AM",
            services: "Enterprise IT Services"
        },
        {
            name: "Applatus Technologies Private Limited",
            rating: 5.0,
            reviews: 11,
            address: "2nd floor, Plot no. 347, Vijay Nagar, Indore",
            hr_phone: "+91 9111107373",
            hr_phone: "+91 9111107374",
            email: "info@applatus.com",
            hr_email: "careers@applatus.com",
            website: "https://applatus.com",
            hours: "Opens 9 AM",
            services: "IT Solutions"
        }
    ];


const itParkCompanies = [
    // {name:"IMPETUS TECHNOLOGIES",rating:4.6,reviews:100,address:"Unit No 4-A, STP-II, Third Floor, Crystal IT Park, Indore",hr_phone:"+91 731 4743000",website:"https://impetus.com",hours:"Open 24 hours",services:"Big Data, Analytics, Cloud Computing"},
    // {name:"YASH Technologies",rating:4.7,reviews:103,address:"Crystal IT PARK STP-1, Ground Floor, Indore",hr_phone:"+91 731 6636363",website:"https://www.yash.com",hours:"Opens 10 AM",services:"Digital Transformation, Cloud, AI/ML"},
    // {name:"InfoBeans Technologies",rating:4.5,reviews:193,address:"2nd Floor, Crystal IT Park, Indore",hr_phone:"+91 731 7162000",website:"https://www.infobeans.com",hours:"Opens 9 AM",services:"Product Engineering"},
    // {name:"Immersive",rating:4.8,reviews:97,address:"604, Atulya IT Park, Indore",hr_phone:"+91 80 62180491",website:"https://immersive.io",hours:"Open 24 hours",services:"PHP, JAVA, .Net, Python, Blockchain"},
    // {name:"Worldpay Inc.",rating:4.4,reviews:93,address:"9th Floor, Crystal IT Park-1, Indore",website:"https://www.worldpay.com",hours:"Open 24 hours",services:"Payment Processing Solutions"},
    // {name:"Linkites",rating:4.3,reviews:123,address:"6th Floor, Crystal IT Park, Indore",hr_phone:"+91 731 2970111",website:"https://linkites.com",hours:"Opens 10 AM",services:"Software Development"}
     {
                name: "IMPETUS TECHNOLOGIES (INDIA) PVT LTD",
                rating: 4.6,
                reviews: 100,
                address: "Unit No 4-A, STP-II, Third Floor, Crystal IT Park, Ring Road, Indore",
                hr_phone: "+91 731 4743000",
                website: "https://impetus.com",
                hours: "Open 24 hours",
                services: "Big Data, Analytics, Cloud Computing",
                review: "Good workplace with great learning opportunities"
            },
            {
                name: "YASH Technologies PVT. LTD.",
                rating: 4.7,
                reviews: 103,
                address: "Crystal IT PARK STP-1, Ground Floor, IT/ITES- SEZ, Khandwa Rd, Indore",
                hr_phone: "+91 731 6636363",
                website: "https://www.yash.com",
                hours: "Opens 10 AM",
                services: "Digital Transformation, Cloud, AI/ML",
                review: "Best place to work and employee friendly company with good amount of hike"
            },
            {
                name: "InfoBeans Technologies Limited",
                rating: 4.5,
                reviews: 193,
                address: "2nd Floor, Crystal IT Park, Bhawarkua Main Rd, Indore",
                hr_phone: "+91 731 7162000",
                website: "https://www.infobeans.com",
                hours: "Opens 9 AM",
                services: "Product Engineering, Digital Solutions",
                review: "One of the most tech company provide for student internship"
            },
            {
                name: "Immersive - Software Development Company",
                rating: 4.8,
                reviews: 97,
                address: "604, Atulya IT Park, Bhawarkua Main Rd, next to Crystal IT Park, Indore",
                hr_phone: "+91 80 62180491",
                website: "https://immersive.io",
                hours: "Open 24 hours",
                services: "PHP, JAVA, .Net, Python, Node JS, Blockchain Development"
            },
            {
                name: "Worldpay Inc.",
                rating: 4.4,
                reviews: 93,
                address: "9th Floor, Crystal IT Park-1, Indore",
                website: "https://www.worldpay.com",
                hours: "Open 24 hours",
                services: "Payment Processing Solutions",
                review: "Nice company to join and you can explore your knowledge here"
            },
            {
                name: "Linkites",
                rating: 4.3,
                reviews: 123,
                address: "6th Floor, Building No 1, Right Side, Crystal IT Park, Indore",
                hr_phone: "+91 731 2970111",
                website: "https://linkites.com",
                hours: "Opens 10 AM",
                services: "Software Development",
                review: "Their team's professionalism, technical expertise"
            },
            {
                name: "Mind Ruby Technologies",
                rating: 4.8,
                reviews: 81,
                address: "5th Floor (Right Side), Building STP-1 Crystal IT Park, Khandwa Rd, Indore",
                hr_phone: "+91 731 2927999",
                website: "https://mindruby.com",
                hours: "Opens 10 AM",
                services: "Custom Software Development, Mobile Apps"
            },
            {
                name: "Vertisystem Global Pvt. Ltd. (A MOURI Tech Company)",
                rating: 4.0,
                reviews: 32,
                address: "1st Floor, Crystal IT Park, STP 2, Khandwa Rd, Indore",
                hr_phone: "+91 731 2972377",
                website: "https://vertisystem.com",
                hours: "Open 24 hours",
                services: "IT Services & Solutions",
                review: "Employee engagement and opportunities for advancement"
            },
            {
                name: "Systango",
                rating: 4.4,
                reviews: 123,
                address: "Crystal IT Park, Building 1, 3rd Floor, Ring Rd, Indore",
                hr_phone: "+91 731 2971030",
                website: "https://www.systango.com",
                hours: "Opens 9 AM",
                services: "Product Development, Mobile & Web Apps",
                review: "This place is awesome for big team projects"
            },
            {
                name: "Hiteshi - Best IT Services",
                rating: 3.8,
                reviews: 118,
                address: "8th Floor Crystal IT Park, Indore",
                hr_phone: "+91 731 2971133",
                website: "https://www.hiteshi.com",
                hours: "Opens 9:30 AM",
                services: "Web & Mobile App Development"
            },
            {
                name: "Hokrix Technologies",
                rating: 5.0,
                reviews: 29,
                address: "Crystal It Park, Rajiv Gandhi Circle, Indore",
                hr_phone: "+91 9993438344",
                website: "https://hokrix.com",
                hours: "Opens 10:30 AM",
                services: "Blockchain & AI Development",
                review: "They have sound knowledge of technology and very flexible in working"
            },
            {
                name: "BitByte Software Technology",
                rating: 4.8,
                reviews: 105,
                address: "402, Atulya IT park, MPIDC, Khandwa Rd, opposite to Indian Coffee House, Indore",
                hr_phone: "+91 731 2970998",
                website: "https://bitbyte.in",
                hours: "Opens 10:30 AM",
                services: "Web & Mobile App Development",
                review: "Team work makes the dream work"
            },
            {
                name: "Quest Global Technologies",
                rating: 4.2,
                reviews: 48,
                address: "Atulya IT park, 202, Indore",
                hr_phone: "+91 9826922447",
                website: "https://questglobaltech.com",
                hours: "Opens 10 AM",
                services: "Engineering Solutions"
            },
            {
                name: "Swap Infotech",
                rating: 4.8,
                reviews: 42,
                address: "601, Atulya IT Park, Bhawarkua Main Rd, Indore",
                hr_phone: "+91 9340606911",
                website: "https://swapinfotech.com",
                hours: "Opens 10 AM",
                services: "IT Solutions"
            },
            {
                name: "Shrinkcom Software Private Limited",
                rating: 4.1,
                reviews: 56,
                address: "Atulya IT Park, 602, Indore",
                hr_phone: "+91 8982525343",
                website: "https://shrinkcom.com",
                hours: "Open 24 hours",
                services: "Software Development"
            },
            {
                name: "InfoGrains",
                rating: 4.4,
                reviews: 156,
                address: "407, Atulya IT Park, Bhawarkua Main Rd, Indore",
                hr_phone: "+91 9617635159",
                website: "https://infograins.com",
                hours: "Opens 10 AM",
                services: "Digital Solutions",
                review: "Their team is highly professional, responsive, and technically sound"
            },
            {
                name: "WebiWork Technologies Pvt. Ltd.",
                rating: 4.7,
                reviews: 11,
                address: "6th floor Atulya IT park, Indore",
                hr_phone: "+91 7692906880",
                website: "https://webiwork.com",
                hours: "Opens 10 AM",
                services: "Web & Mobile Development"
            },
            {
                name: "Amstech Incorporation Private Limited",
                rating: 4.9,
                reviews: 36,
                address: "3rd Floor, Veda Business Park, 314, Bhawarkua Main Rd, near Crystal IT Park, Indore",
                hr_phone: "+91 9993126869",
                website: "https://amstechinc.com",
                hours: "Opens 10 AM",
                services: "Software Solutions",
                review: "The work environment at 'Amstech' is simply wonderful"
            },
            {
                name: "Engineer Philosophy Web Services Pvt. Ltd.",
                rating: 4.6,
                reviews: 35,
                address: "205, Atulya IT Park, Khandwa Rd, Indore",
                hr_phone: "+91 9131589465",
                website: "https://engineerphilosophy.com",
                hours: "Opens 9:30 AM",
                services: "Web Development",
                review: "Great place to learn, excel and implement my skills"
            },
            {
                name: "SynergyTop Inc",
                rating: 4.6,
                reviews: 63,
                address: "114 Ground Floor, IT Park, New IT Park Building, 142-A, Indore",
                hr_phone: "+91 7879123770",
                website: "https://synergytop.com",
                hours: "Open 24 hours",
                services: "Software Development & Consulting",
                review: "One of the best IT companies of central India!"
            },
            {
                name: "Impetus Technologies India Pvt. Ltd.",
                rating: 4.5,
                reviews: 113,
                address: "Sarda House, 24-B, AB Rd, near Crystal IT Park, Indore",
                hr_phone: "+91 731 4269300",
                website: "https://www.impetus.com",
                hours: "Opens 9 AM",
                services: "Big Data & Analytics"
            },
            {
                name: "Vista IT Solutions Pvt. Ltd.",
                rating: 4.3,
                reviews: 112,
                address: "142-A, New IT Park building, Indore",
                website: "https://vistaitsolutions.com",
                hours: "Opens 11:30 AM",
                services: "IT Solutions",
                review: "The environment of the company is professional"
            },
            {
                name: "IT Spark Technology Pvt. Ltd.",
                rating: 4.8,
                reviews: 69,
                address: "4th Floor 418 Shekhar Central Manoramaganj, near IT Park, Indore",
                hr_phone: "+91 9109845654",
                website: "https://itspark.in",
                hours: "Opens 10:30 AM",
                services: "Software Development",
                review: "They helped us quickly and precisely on different projects"
            },
            {
                name: "Parkhya Solutions Pvt. Ltd.",
                rating: 4.3,
                reviews: 144,
                address: "121, Devi Ahilya Marg, near IT Park, Indore",
                website: "https://parkhya.com",
                hours: "Opens 9:30 AM",
                services: "Software Solutions"
            },
            {
                name: "Young Decade IT Software Solution",
                rating: 4.7,
                reviews: 533,
                address: "office No 202, 2nd floor, Gracia Heights, Devi Ahilya Marg, above HDFC Bank, Indore",
                hr_phone: "+91 7987611372",
                website: "https://youngdecade.com",
                hours: "Opens 9:30 AM",
                services: "Software Development"
            },
            {
                name: "Conative IT Solutions Pvt. Ltd.",
                rating: 4.0,
                reviews: 129,
                address: "Office No. 217-218, Onam Plaza, Infront of IBus Stop, beside Industry house, Indore",
                hr_phone: "+91 8269788173",
                website: "https://conative.in",
                hours: "Opens 10 AM",
                services: "IT Solutions"
            },
            {
                name: "Sofmen Technologies Private Limited",
                rating: 4.1,
                reviews: 53,
                address: "508, Rafael Tower, 8/2, near IT Park, Indore",
                hr_phone: "+91 731 2565222",
                website: "https://sofmen.com",
                hours: "Opens 10 AM",
                services: "Software Development",
                review: "Good environment, Good behaviour and Great place to learning / Work"
            },
            {
                name: "qualwebs",
                rating: 4.7,
                reviews: 74,
                address: "203, 9930 Spaces 4, Mangal Nagar, Near Rajeev Gandhi Square, AB Rd, Indore",
                hr_phone: "+91 8827796669",
                website: "https://qualwebs.com",
                hours: "Open 24 hours",
                services: "Web Development",
                review: "Amazing company with great projects!"
            },
            {
                name: "Technorizen Software Solution",
                rating: 4.7,
                reviews: 341,
                address: "Sapphire House, 402 A, B, C, Sapna Sangeeta Rd, Indore",
                hr_phone: "+91 7828407092",
                website: "https://technorizen.com",
                hours: "Opens 10 AM",
                services: "Mobile Apps, AI/ML, Blockchain, Digital Marketing"
            },
            {
                name: "Software Technology Parks Of India",
                rating: 4.4,
                reviews: 78,
                address: "New IT Park Building, Atmaram Choudhary Marg, opp. Sukhliya, Indore",
                hr_phone: "+91 731 4030880",
                website: "https://www.stpi.in",
                hours: "Opens 9:30 AM",
                services: "IT Infrastructure & Support"
            },
            {
                name: "EMPOWER INTEGRATED SOLUTIONS (P) LTD.",
                rating: 4.4,
                reviews: 34,
                address: "IT Park, New IT Park Building, Office No. 110, Ground Floor Right Wing, 142 A, Indore",
                hr_phone: "+91 9826027230",
                website: "https://empoweris.com",
                hours: "Opens 9 AM",
                services: "Custom Software Development",
                review: "They offers best customized software development services"
            },
            {
                name: "Logical Soft Tech Private Limited",
                rating: 4.4,
                reviews: 149,
                address: "388, PU4, next to Krozzon Hotel, near IT Park, Indore",
                hr_phone: "+91 8210251824",
                website: "https://logicalsofttech.com",
                hours: "Opens 10 AM",
                services: "Mobile App, Website Development, SEO/SMM",
                review: "Best software company for work with lots of learning opportunities"
            },
            {
                name: "Atulya IT Park",
                rating: 4.3,
                reviews: 202,
                address: "Bhawarkua Main Road, Indore, Madhya Pradesh",
                hr_phone: "+91 7771077700",
                website: "https://atulyaitpark.com",
                hours: "Open 24 hours",
                services: "IT Park Complex",
                review: "Companies and well maintained"
            },
            {
                name: "IT park indore",
                rating: 4.3,
                reviews: 303,
                address: "Khandwa Rd, Indore",
                services: "Technology Park",
                review: "High quality companies and so are the security and features"
            },
            {
                name: "Crystal IT Park",
                rating: 4.4,
                reviews: 2700,
                address: "MVPC+8WC, Indore",
                hours: "Opens 12 AM",
                services: "IT Park Complex",
                review: "Very big it companies are located in crystal park"
            },
            {
                name: "Sinhasa IT Park",
                rating: 4.2,
                reviews: 86,
                address: "IT Park, 28, Indore - Dhar Rd, Indore",
                hours: "Open 24 hours",
                services: "Technology Park",
                review: "Highly recommend for anyone looking to set up operations in Indore!"
            }
];

// Vadodara Companies Data
const vadodaraGotri = [
    {
            name: "Helios Solutions",
            rating: 4.8,
            reviews: 200,
            address: "802, Iscon Atria 2, Gotri Road, Vadodara – 390021, Gujarat",
            hr_phone: "+91 9879717763",
            hr_phone: "+91 9879717764",
            email: "info@heliossolutions.in",
            hr_email: "hr@heliossolutions.in",
            website: "https://heliossolutions.in",
            hours: "Opens 10 AM",
            services: "IoT, AI, AR, VR, Big Data, Chatbot, Blockchain, Software Development",
            employees: "200+",
            founded: "2008",
            review: "15 years of experience delivering 400+ success stories"
        },
        {
            name: "Spaculus Software Pvt. Ltd.",
            rating: 4.7,
            reviews: 150,
            address: "13th Floor, Vihav Supremus, Off, Gotri Rd, near Iscon Heights, Gotri, Vadodara, Gujarat 390021",
            hr_phone: "+91 9825012345",
            hr_phone: "+91 9825012346",
            email: "info@spaculus.com",
            hr_email: "careers@spaculus.com",
            website: "https://spaculus.com",
            hours: "Opens 10 AM",
            services: "Software Development, Mobile Apps, Web Development",
            employees: "150+",
            founded: "2008",
            certifications: "ISO 9001, ISO 27001",
            review: "Leading offshore software development company"
        },
        {
            name: "Atliq Technologies",
            rating: 4.5,
            reviews: 80,
            address: "Gotri Road, Vadodara, Gujarat 390021",
            hr_phone: "+91 9998765432",
            hr_phone: "+91 9998765433",
            email: "info@atliqtech.com",
            hr_email: "hr@atliqtech.com",
            website: "https://atliqtech.com",
            hours: "Opens 9:30 AM",
            services: "IT Solutions, Software Development",
            employees: "60+",
            founded: "2012"
        },
        {
            name: "Inbox Infotech",
            rating: 4.6,
            reviews: 95,
            address: "Gotri Road, Vadodara, Gujarat 390021",
            hr_phone: "+91 9876543210",
            hr_phone: "+91 9876543211",
            email: "contact@inboxinfotech.com",
            hr_email: "hr@inboxinfotech.com",
            website: "https://inboxinfotech.com",
            hours: "Opens 10 AM",
            services: "Web Development, Mobile Apps, IT Infrastructure",
            employees: "80+",
            founded: "2009",
            review: "Customized quality solutions for global clientele"
        },
        {
            name: "Webmyne Systems Pvt. Ltd.",
            rating: 4.7,
            reviews: 180,
            address: "Ivory Terrace, 702, RC Dutt Rd, near Gotri Road, Vadodara, Gujarat 390007",
            hr_phone: "+91 2653506000",
            hr_phone: "+91 2653506001",
            email: "info@webmyne.com",
            hr_email: "careers@webmyne.com",
            website: "https://webmyne.com",
            hours: "Opens 10 AM",
            services: "Software Development, Digital Solutions",
            employees: "180+",
            founded: "2000",
            review: "More than two decades of IT service excellence"
        },
        {
            name: "CDL IT Solutions",
            rating: 4.6,
            reviews: 70,
            address: "329, Arena, Nilamber Corporate Park, Vasna Gotri Link Road, Vadodara, 390007",
            hr_phone: "+91 265 3928697",
            hr_phone: "+91 265 3928698",
            email: "info@cdl-it.com",
            hr_email: "hr@cdl-it.com",
            website: "https://cdl-it.com",
            hours: "Opens 9 AM",
            services: "3PL Logistics Solutions, IT Services",
            employees: "100+",
            founded: "2011"
        },
        {
            name: "NetWeb Software",
            rating: 4.7,
            reviews: 120,
            address: "404-405, Sears Tower, Gotri – Sevasi Road, Main Road, Vadodara-391101 Gujarat",
            hr_phone: "+91 9662398895",
            hr_phone: "+91 9662398896",
            email: "info@netwebindia.com",
            hr_email: "careers@netwebindia.com",
            website: "https://netwebindia.com",
            hours: "Opens 10 AM",
            services: "AI Solutions, Product Development, RPA, Mobile Development",
            employees: "500+",
            founded: "2005",
            review: "High-end software solution provider with global reach"
        },
        {
            name: "Collabera Technologies Pvt Ltd",
            rating: 4.5,
            reviews: 90,
            address: "Gotri Sevasi Road, Gotri, Vadodara Gujarat, 390021",
            hr_phone: "+91 9876543211",
            hr_phone: "+91 9876543212",
            email: "info@collabera.com",
            hr_email: "recruitment@collabera.com",
            website: "https://www.collabera.com",
            hours: "Opens 9 AM",
            services: "Data Analytics, AI, Robotics, IOT",
            employees: "300+",
            founded: "1991",
            review: "MNC providing cutting-edge technology solutions"
        },
        {
            name: "Iscon Atria IT Hub (Multiple Companies)",
            rating: 4.6,
            reviews: 150,
            address: "305, Iscon Atria-1, Gotri Road, Vadodara - 390021",
            hr_phone: "+91 9825000000",
            hr_phone: "+91 9825000001",
            email: "info@isconatria.com",
            hr_email: "leasing@isconatria.com",
            website: "https://isconatria.com",
            hours: "Opens 9:30 AM",
            services: "IT Park hosting multiple IT companies",
            review: "Premium IT park with modern infrastructure"
        },
        {
            name: "Sage Infotech",
            rating: 4.5,
            reviews: 85,
            address: "403, Iscon Atria-2, Gotri Road, Vadodara, Gujarat 390021",
            hr_phone: "+91 265 6540000",
            hr_phone: "+91 265 6540001",
            email: "info@sageinfotech.co.in",
            hr_email: "careers@sageinfotech.co.in",
            website: "https://sageinfotech.co.in",
            hours: "Opens 10 AM",
            services: "Software Development, IT Solutions",
            employees: "120+",
            founded: "2010"
        },
        {
            name: "Radixweb",
            rating: 4.7,
            reviews: 165,
            address: "603-604, Sears Tower, Gotri - Sevasi Road, Vadodara, Gujarat 391101",
            hr_phone: "+91 265 3568000",
            hr_phone: "+91 265 3568001",
            email: "info@radixweb.com",
            hr_email: "hr@radixweb.com",
            website: "https://radixweb.com",
            hours: "Opens 9:30 AM",
            services: "Web & Mobile Development, Cloud Solutions",
            employees: "400+",
            founded: "2000",
            review: "20+ years of digital innovation"
        },
        {
            name: "Magneto IT Solutions",
            rating: 4.6,
            reviews: 135,
            address: "701, Iscon Elegance, Near Iscon Circle, Gotri Road, Vadodara, Gujarat 390021",
            hr_phone: "+91 265 3580000",
            hr_phone: "+91 265 3580001",
            email: "info@magnetoitsolutions.com",
            hr_email: "careers@magnetoitsolutions.com",
            website: "https://magnetoitsolutions.com",
            hours: "Opens 10 AM",
            services: "E-commerce Development, Magento Solutions",
            employees: "250+",
            founded: "2009"
        },
        {
            name: "Sigma IT Solutions",
            rating: 4.5,
            reviews: 92,
            address: "502, Vertex Building, Gotri - Sevasi Road, Vadodara, Gujarat 391101",
            hr_phone: "+91 265 3590000",
            hr_phone: "+91 265 3590001",
            email: "info@sigmait.co.in",
            hr_email: "hr@sigmait.co.in",
            website: "https://sigmait.co.in",
            hours: "Opens 9 AM",
            services: "IT Infrastructure, Software Solutions",
            employees: "90+",
            founded: "2013"
        }
];

const vadodaraAkota = [
        {
            name: "Infosys Limited",
            rating: 5.0,
            reviews: 500,
            address: "Indiabulls Mega Mall, SF-18E, Akota Rd, Anand Nagar, Haripura, Vadodara, Gujarat 390020",
            hr_phone: "+91 80 41563998",
            hr_phone: "+91 80 28522000",
            email: "askus@infosys.com",
            hr_email: "careers@infosys.com",
            website: "https://www.infosys.com",
            hours: "Opens 9 AM",
            services: "IT Consulting, Digital Transformation, Cloud Services, ERP",
            employees: "10000+",
            review: "Leading global IT consulting and services company",
            salary: "Entry: ₹3.2L-5L, Mid: ₹6L-10L, Senior: ₹12L-22L per annum"
        },
        {
            name: "IBM India Private Limited",
            rating: 4.9,
            reviews: 450,
            address: "89, Sheetal Nagar, Akota, Vadodara, Gujarat 390020",
            hr_phone: "+91 80 40114047",
            hr_phone: "+91 80 40114048",
            email: "rccindia@in.ibm.com",
            hr_email: "ibmindiacareers@in.ibm.com",
            website: "https://www.ibm.com",
            hours: "Opens 9 AM",
            services: "Cloud Computing, AI, Machine Learning, Blockchain, Data Analytics, Cybersecurity",
            employees: "5000+",
            review: "Global technology and innovation leader",
            salary: "Entry: ₹4L-6.5L, Mid: ₹7L-14L, Senior: ₹15L-30L per annum"
        },
        {
            name: "Adri IT Solutions",
            rating: 4.7,
            reviews: 110,
            address: "Samanvay Silver, 801-802, Besides Hotel Royal Orchid, Mujmahuda Rd, Pratham Avenue, Akota, Vadodara, Gujarat 390007",
            hr_phone: "+91 9825123456",
            hr_phone: "+91 9825123457",
            email: "info@adriitsolutions.com",
            hr_email: "hr@adriitsolutions.com",
            website: "https://adriitsolutions.com",
            hours: "Opens 10 AM",
            services: "Web Development, Desktop Apps, Mobile Apps, IT Solutions",
            employees: "150+",
            founded: "2005",
            review: "Complete team of professionals with expertise in software development"
        },
        {
            name: "Aditya Infotech",
            rating: 4.4,
            reviews: 65,
            address: "Akota, Vadodara-390020, Gujarat",
            hr_phone: "+91 9909876543",
            hr_phone: "+91 9909876544",
            email: "info@adityainfotech.co.in",
            hr_email: "careers@adityainfotech.co.in",
            website: "https://adityainfotech.co.in",
            hours: "Opens 9:30 AM",
            services: "Web Design, Software Development",
            employees: "40+",
            founded: "2011",
            review: "Local IT service provider with customer focus"
        },
        {
            name: "Concentrix",
            rating: 4.6,
            reviews: 800,
            address: "Near Akota, Vadodara, Gujarat 390020",
            hr_phone: "+91 2653500000",
            hr_phone: "+91 2653500001",
            email: "info.india@concentrix.com",
            hr_email: "careers.india@concentrix.com",
            website: "https://www.concentrix.com",
            hours: "24/7 Operations",
            services: "Customer Experience Solutions, Business Services",
            employees: "2000+",
            review: "Multinational business services firm with customer-focused solutions"
        },
        {
            name: "Webdew",
            rating: 4.8,
            reviews: 140,
            address: "Near HDFC Bank, Sheetal Nagar, Akota, Vadodara, Gujarat 390010",
            hr_phone: "+91 9998877665",
            hr_phone: "+91 9998877666",
            email: "hello@webdew.com",
            hr_email: "careers@webdew.com",
            website: "https://webdew.com",
            hours: "Opens 10 AM",
            services: "Digital Solutions, Web Development, IT Services",
            employees: "100+",
            founded: "2014",
            review: "Core valued IT company with integrity and passion"
        },
        {
            name: "TCS (Tata Consultancy Services)",
            rating: 4.7,
            reviews: 380,
            address: "Indiabulls Mega Mall, 3rd Floor, Akota Road, Vadodara, Gujarat 390020",
            hr_phone: "+91 265 6700000",
            hr_phone: "+91 265 6700001",
            email: "contact.vadodara@tcs.com",
            hr_email: "careers.vadodara@tcs.com",
            website: "https://www.tcs.com",
            hours: "Opens 9 AM",
            services: "IT Services, Consulting, Digital Transformation",
            employees: "3000+",
            review: "India's largest IT services company",
            salary: "Entry: ₹3.5L-4.5L, Mid: ₹6L-12L, Senior: ₹15L-28L per annum"
        },
        {
            name: "Tech Mahindra",
            rating: 4.6,
            reviews: 290,
            address: "Sheetal Nagar, Near Akota Garden, Akota, Vadodara, Gujarat 390020",
            hr_phone: "+91 265 6710000",
            hr_phone: "+91 265 6710001",
            email: "info.vadodara@techmahindra.com",
            hr_email: "careers.vadodara@techmahindra.com",
            website: "https://www.techmahindra.com",
            hours: "Opens 9:30 AM",
            services: "IT Services, Network Services, Digital Solutions",
            employees: "1500+",
            founded: "1986",
            salary: "Entry: ₹3.5L-5L, Mid: ₹6L-13L, Senior: ₹14L-25L per annum"
        },
        {
            name: "Cybage Software",
            rating: 4.5,
            reviews: 175,
            address: "Samanvay Silver Complex, Akota, Vadodara, Gujarat 390007",
            hr_phone: "+91 265 6720000",
            hr_phone: "+91 265 6720001",
            email: "info.vadodara@cybage.com",
            hr_email: "recruitment.vadodara@cybage.com",
            website: "https://www.cybage.com",
            hours: "Opens 10 AM",
            services: "Product Engineering, Quality Engineering, Digital Services",
            employees: "800+",
            founded: "1995"
        },
        {
            name: "Hexaware Technologies",
            rating: 4.6,
            reviews: 210,
            address: "301-302, Samanvay Silver, Akota Road, Vadodara, Gujarat 390007",
            hr_phone: "+91 265 6730000",
            hr_phone: "+91 265 6730001",
            email: "info@hexaware.com",
            hr_email: "careers@hexaware.com",
            website: "https://hexaware.com",
            hours: "Opens 9 AM",
            services: "IT Consulting, Digital Transformation, Cloud Solutions",
            employees: "1200+",
            founded: "1990"
        }
    ];

const vadodaraAlkapuri = [
    // {name:"Dhrup IT Solutions",rating:4.8,reviews:130,address:"National Plaza, S7, RC Dutt Rd, Alkapuri, Vadodara",hr_phone:"+91 9825678901",website:"https://dhrupit.com",hours:"Opens 10 AM",services:"Software Development, IT Solutions"},
    // {name:"Rishabh Software",rating:4.8,reviews:200,address:"Alkapuri Area, Vadodara",hr_phone:"+91 2653500123",website:"https://www.rishabhsoft.com",hours:"Opens 9:30 AM",services:"Software Development, Cloud Solutions"},
    // {name:"Nivida Web Solutions",rating:4.7,reviews:145,address:"305, Privilege Avenue, Vadodara",hr_phone:"+91 9876543234",website:"https://nivida.com",hours:"Opens 10 AM",services:"Web Solutions, IT Consulting"}

     {
            name: "Dhrup IT Solutions Pvt Ltd",
            rating: 4.8,
            reviews: 130,
            address: "National Plaza, S7, RC Dutt Rd, Aradhana Society, Vishwas Colony, Alkapuri, Vadodara, Gujarat 390007",
            hr_phone: "+91 9825678901",
            email: "info@dhrupit.com",
            hr_email: "hr@dhrupit.com",
            website: "https://dhrupit.com",
            hours: "Opens 10 AM",
            services: "Software Development, IT Solutions, Digital Marketing",
            founded: "2016",
            employees: "100+",
            review: "MNC specializing in bespoke IT solutions worldwide"
        },
        {
            name: "CDL Logistics IT",
            rating: 4.6,
            reviews: 85,
            address: "301, 302 Yogi Complex, near Relish Hotel, Sampatrao Colony, Alkapuri, Vadodara, Gujarat 390005",
            hr_phone: "+91 9081234787",
            email: "info@cdl-it.com",
            hr_email: "careers@cdl-it.com",
            website: "https://cdl-it.com",
            hours: "Opens 9 AM",
            services: "3PL Logistics Solutions, IT Management",
            founded: "2011",
            review: "Major UK 3PL logistics brand with Vadodara operations"
        },
        {
            name: "Softcom Industry",
            rating: 4.7,
            reviews: 105,
            address: "702, Ivory Terrace, Opp. Circuit House, R.C. Dutt Road, Vadodara-07 Gujarat",
            hr_phone: "+91 2652345678",
            email: "info@softcomindustry.com",
            hr_email: "hr@softcomindustry.com",
            website: "https://softcomindustry.com",
            hours: "Opens 9:30 AM",
            services: "IT Infrastructure, Technology Solutions",
            review: "Well established IT infrastructure company with global operations"
        },
        {
            name: "Ethics Infotech LLP",
            rating: 4.7,
            reviews: 92,
            address: "SampatRao Colony, Opp. Circuit House, Near Baroda Laparoscopy Centre, Alkapuri, Vadodara Gujarat, India- 390007",
            hr_phone: "+91 9998765444",
            email: "info@ethicsinfotech.com",
            hr_email: "careers@ethicsinfotech.com",
            website: "https://ethicsinfotech.com",
            hours: "Opens 10 AM",
            services: "ERP Software, Business Solutions",
            founded: "2018",
            review: "Best ERP software provider in India at cost-effective rates"
        },
        {
            name: "Bit Infotech",
            rating: 4.6,
            reviews: 78,
            address: "901-903, 9th Floor, Neptune Edge, Sarabhai Compound, Next to Neptune Trinity, Near Genda Circle, Vadodara – 390007",
            hr_phone: "+91 2653456789",
            email: "info@bitinfotech.com",
            hr_email: "hr@bitinfotech.com",
            website: "https://bitinfotech.com",
            hours: "Opens 9 AM",
            services: "IT Services, Engineering Design",
            founded: "2007",
            review: "Pioneer in IT and Engineering Design services globally"
        },
        {
            name: "Nivida Web Solutions Pvt Ltd",
            rating: 4.7,
            reviews: 145,
            address: "305, Privilege Avenue, Opp. Isha Hospital, behind Atlantis Sarabhai campus, Sarabhai Rd, Vadiwadi, Vadodara, Gujarat 390023",
            hr_phone: "+91 9876543234",
            email: "info@nivida.com",
            hr_email: "careers@nivida.com",
            website: "https://nivida.com",
            hours: "Opens 10 AM",
            services: "Web Solutions, IT Consulting, Software Development",
            founded: "2007",
            employees: "150+",
            review: "15 years of experience serving global clients in 7 countries"
        },
        {
            name: "Rishabh Software",
            rating: 4.8,
            reviews: 200,
            address: "Alkapuri Area, Vadodara, Gujarat",
            hr_phone: "+91 2653500123",
            email: "info@rishabhsoft.com",
            hr_email: "careers@rishabhsoft.com",
            website: "https://www.rishabhsoft.com",
            hours: "Opens 9:30 AM",
            services: "Software Development, Digital Transformation, Cloud Solutions",
            employees: "500+",
            founded: "2000",
            review: "Trusted technology partner with impressive infrastructure"}
];

const vadodaraGorwa = [
    // {name:"L&T Technology Services",rating:4.9,reviews:350,address:"L&T Knowledge City, SEZ, Vadodara",hr_phone:"+91 2663008000",website:"https://www.ltts.com",hours:"Opens 9 AM",services:"Engineering R&D, Digital Engineering"},
    // {name:"Reliance Industries IT",rating:4.7,reviews:280,address:"Near Genda Circle, Gorwa, Vadodara",hr_phone:"+91 2262816000",website:"https://www.ril.com",hours:"Opens 9 AM",services:"IT Services, Digital Solutions"},
    // {name:"Symantec Software",rating:4.6,reviews:190,address:"Near Genda Circle, Gorwa, Vadodara",hr_phone:"+91 2653456123",website:"https://www.broadcom.com",hours:"Opens 9:30 AM",services:"Cybersecurity, Enterprise Security"}

    {
            name: "L&T Technology Services (LTTS)",
            rating: 4.9,
            reviews: 350,
            address: "L&T Knowledge City, Special Economic Zone (IT/ITES), West Block – II, NH No. 8, Village Ankhol, Vadodara, Gujarat, 390019",
            hr_phone: "+91 2663008000",
            email: "business.relations@ltts.com",
            hr_email: "recruitment@ltts.com",
            website: "https://www.ltts.com",
            hours: "Opens 9 AM",
            services: "Engineering R&D, Digital Engineering, Embedded Systems, Industrial Automation, AI, IoT",
            employees: "5000+",
            review: "Global leader in engineering research and development services",
            salary: "Entry: ₹4L-7L, Mid: ₹8L-15L, Senior: ₹16L-35L per annum"
        },
        {
            name: "Reliance Industries Ltd - IT Division",
            rating: 4.7,
            reviews: 280,
            address: "Near Genda Circle, Gorwa, Vadodara, Gujarat",
            hr_phone: "+91 2262816000",
            email: "corporate@ril.com",
            hr_email: "careers@ril.com",
            website: "https://www.ril.com",
            hours: "Opens 9 AM",
            services: "IT Services, Digital Solutions, Enterprise Systems",
            employees: "1000+",
            review: "Leading conglomerate with strong IT presence"
        },
        {
            name: "Symantec Software Solutions Pvt Ltd",
            rating: 4.6,
            reviews: 190,
            address: "Near Genda Circle, Gorwa, Vadodara, Gujarat",
            hr_phone: "+91 2653456123",
            email: "info.india@broadcom.com",
            hr_email: "careers.india@broadcom.com",
            website: "https://www.broadcom.com",
            hours: "Opens 9:30 AM",
            services: "Cybersecurity, Enterprise Security Solutions",
            employees: "800+",
            review: "Multinational corporation specializing in security solutions"
        },
        {
            name: "C-Metric Pvt Ltd",
            rating: 4.5,
            reviews: 75,
            address: "Gorwa Area, Vadodara, Gujarat",
            hr_phone: "+91 9876543456",
            email: "info@cmetric.in",
            hr_email: "hr@cmetric.in",
            website: "https://cmetric.in",
            hours: "Opens 10 AM",
            services: "IT Solutions, Software Development",
            review: "Innovative IT company providing tech solutions"
        },
        {
            name: "Oasis Organisation",
            rating: 4.6,
            reviews: 88,
            address: "Gorwa, Vadodara, Gujarat",
            hr_phone: "+91 9988776655",
            email: "contact@oasisorganisation.com",
            hr_email: "careers@oasisorganisation.com",
            website: "https://oasisorganisation.com",
            hours: "Opens 9:30 AM",
            services: "IT Services, Business Solutions",
            review: "Established IT company with diverse service portfolio"
        }
    
];

// ===== EXPORT ALL DATA =====
// This makes the data available to other files
// window.CompanyData = {
//     vijayNagarCompanies,
//     itParkCompanies,
//     vadodaraGotri,
//     vadodaraAkota,
//     vadodaraAlkapuri,
//     vadodaraGorwa
// };